service: brodeynewman

package:
  include:
    - serverless/**/*.js
    - serverless/**/*.map.js
  exclude:
    - src/**/*
    - serverless/**/*.test.js
    - serverless/**/*.spec.js
    - node_modules/aws-sdk/**

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./config/webpack.serverless.js

provider:
  name: aws
  runtime: nodejs8.10
  region: 'us-east-1'
  endpointType: regional
  timeout: 10
  memorySize: 256
  profile: 'default'

  environment:
    EMAIL: brodeynewman@gmail.com

functions:
  handle_email:
    handler: serverless/functions/handle_email/index.handler
    events:
      - http:
          path: /email
          method: post